# Generated by Django 5.0.7 on 2024-12-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_view_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='post_pics'),
        ),
    ]
